default_install_hook_types: [pre-commit, post-checkout, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/UnknownPlatypus/djangofmt-pre-commit
    rev: v0.2.5
    hooks:
      - id: djangofmt
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: local
    hooks:
      - id: sync-uv-packages
        name: Sync UV Packages
        entry: uv sync
        language: system
        pass_filenames: false
        always_run: true
        stages: [ post-checkout ]
      - id: tests
        name: Run Unit Tests
        entry: uv run pytest --ignore=e2e -n auto
        language: system
        always_run: true
        pass_filenames: false
        stages: [ pre-push ]
      - id: mypy
        name: Run MyPy
        entry: uv run mypy .
        language: system
        always_run: true
        pass_filenames: false
        stages: [ pre-push ]
      - id: run-tailwindcss-build
        name: Run TailwindCSS Build
        entry: npm run styles:build
        pass_filenames: false
        always_run: true
        language: system
        stages: [post-checkout]
