repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/UnknownPlatypus/djangofmt-pre-commit
    rev: v0.2.5
    hooks:
      - id: djangofmt
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1  # Match your pyproject.toml version
    hooks:
      - id: mypy
        stages: [ pre-push ]
        pass_filenames: false
        always_run: true
        args: ["."]
        additional_dependencies:
            - python-dotenv>=1.2.1
            - django-stubs[compatible-mypy]>=5.2.8
            - wagtail>=7.2
            - factory-boy>=3.3.3
  - repo: local
    hooks:
      - id: tests
        name: Run Tests
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: run-tailwindcss-build
        name: Run TailwindCSS Build
        entry: npm run styles:build
        pass_filenames: false
        language: system
        stages: [post-checkout]
