name: urban-platform-staging

services:
  web:
    container_name: urban-platform-staging-web
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
    command: uv run gunicorn urban_platform.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - uv_cache:/app/.cache/uv
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    depends_on:
      - db
      - cache
    restart: always
    networks:
      - internal

  nginx:
    container_name: urban-platform-staging
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    hostname: urban-platform-staging
    depends_on:
      - web
    restart: always
    networks:
      - nginx
      - internal

  cache:
    image: redis:7.4.2
    command: redis-server --save 20 1 --loglevel warning
    restart: always
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  worker:
    container_name: urban-platform-staging-worker
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
    command: uv run celery -A urban_platform worker --loglevel=info
    volumes:
      - media_volume:/app/mediafiles
      - uv_cache:/app/.cache/uv
    env_file:
      - .env
    depends_on:
      - db
      - cache
    restart: always
    networks:
      - internal

#  celery_beat:
#    container_name: urban-platform-staging-celery-beat
#    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
#    command: uv run celery -A urban_platform beat --loglevel=info
#    volumes:
#      - uv_cache:/app/.cache/uv
#    env_file:
#      - .env
#    depends_on:
#      - db
#      - cache
#    restart: always
#    networks:
#      - internal

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    networks:
      - internal

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
    driver: local
  uv_cache:

networks:
  internal:
  nginx:
    external: true
    name: nginx
