name: CI Pipeline

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_call:

jobs:
  quality:
    name: Quality (${{ matrix.check }})
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: urban_platform.settings.test
      SECRET_KEY: "test-key"
      ENVIRONMENT: "test"

    strategy:
      fail-fast: false
      matrix:
        check: [lint, format, types]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Install Ruff
        run: uv tool install ruff

      - name: Run Ruff Linter
        if: matrix.check == 'lint'
        run: uv run ruff check --output-format=github

      - name: Run Ruff Formatter
        if: matrix.check == 'format'
        run: uv run ruff format --check

      - name: Run Mypy Type Checker
        if: matrix.check == 'types'
        run: uv run mypy .

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tests: [ unit, e2e ]

    env:
      DJANGO_SETTINGS_MODULE: urban_platform.settings.test
      SECRET_KEY: "test-key"
      ENVIRONMENT: "test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Install Playwright browsers
        run: |
          uv run playwright install --with-deps chromium

      - name: Run Unit Tests
        if: matrix.tests == 'unit'
        run: uv run pytest --ignore e2e -n auto --junitxml=test-results-unit.xml

      - name: Upload Unit Test Results
        if: matrix.tests == 'unit' && always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results-unit
          path: test-results-unit.xml

      - name: Run End-to-End Tests
        if: matrix.tests == 'e2e'
        run: uv run pytest e2e -n auto --junitxml=test-results-e2e.xml

      - name: Upload E2E Test Results
        if: matrix.tests == 'e2e' && always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results-e2e
          path: test-results-e2e.xml
